export default class CommonConstants {
  static readonly FULL_LENGTH: string = '100%'
  static readonly TITLE_WIDTH: string = '80%'
  static readonly LIST_DEFAULT_WIDTH: string = '93.3%'
  static readonly OPACITY_DEFAULT: number = 1
  static readonly OPACITY_COMPLETED: number = 0.4
  static readonly BORDER_RADIUS: number = 24
  static readonly FONT_WEIGHT: number = 500
  static readonly COLUMN_SPACE: number = 16
  static readonly TODO_DATA: Array<string> = [
    "起床",
    "刷牙洗脸",
    "吃早餐",
    "送娃上学",
    "上班",
    "搬砖",
    "下班",
    "喝茶",
  ]
}


