

export class BACommonConstant {

  static readonly kFULL_WIDTH: string = '100%';
  static readonly kFULL_HEIGHT: string = '100%';

  // static readonly kPAGE_WEB_URI: string = "src/feature/tab1/WebComponent/pages/BAWebPage"
  static readonly kPAGE_WEB_URI: string = "/pages/BAWebPage"

  // static readonly

  static readonly WebConstant_DURATION: number = 3000;
  static readonly WebConstant_PROGRESS_MIN: number = 0;
  static readonly WebConstant_PROGRESS_MAX: number = 100;
  static readonly WebConstant_PROGRESS_STEP: number = 10;
  static readonly WebConstant_MILLI_SECONDS: number = 100;
  static readonly WebConstant_PROGRESS_STROKE_WIDTH: number = 15;
  static readonly WebConstant_PROGRESS_SCALE_COUNT: number = 15;
  static readonly WebConstant_PROGRESS_SCALE_WIDTH: number = 5;
  static readonly WebConstant_PROGRESS_WIDTH: number = 80;
  static readonly WebConstant_PROGRESS_POSITION_X: string = '40%';
  static readonly WebConstant_PROGRESS_POSITION_Y: string = '30%';


}
