
export const SECOND_PAGE: string = "pages/BAVideoPlayView"
export const SOURCE: string = 'source'
export const NET: string = 'video url'
export const MESSAGE: string = '请检查网络'
export const START_TIME: string = '00:00'
export const ZERO_STR: string = '0'
export const SPLIT: string = ':'
export const DEFAULT_OPACITY: number = Number.parseFloat('0.2')
export const SMALL_TRACK_THICK_NESS: number = 2
export const BIG_TRACK_THICK_NESS: number = 4
export const COMMON_NUM_DOUBLE: number = 10
export const COMMON_NUM_MINUTE: number = 60
export const COMMON_NUM_FONT_WEIGHT: number = 500
export const COMMON_NUM_DURATION: number = 5000
export const LIST: string[] = ['最近播放', '为你推荐']
export const ALL_PERCENT: string = '100%'
export const IMAGE_SIZE: number = 24

export const enum STRING_PERCENT {
  SLIDER_WITH = '46.7%',
  NINETY_PERCENT = '88%',
  INDEX_COMPONENT_WIDTH_PERCENT = '93.3%',
  INDEX_SWIPER_HEIGHT_PERCENT = '24.1%',
  INDEX_MODULE_HEIGHT_PERCENT = '22.8%',
  INDEX_SWIPER_LEFT_RIGHT_MARGIN = '3.3%'
}

export const enum MARGIN_FONT_SIZE {
  FIRST_MARGIN = 12,
  SECOND_MARGIN = 16,
  THIRD_MARGIN = 18,
  FOURTH_MARGIN = 24,
  FIFTH_MARGIN = 50,
  SIXTH_MARGIN = 94,
  SEVENTH_MARGIN = 132
}

export const enum VIDEO_TYPE {
  INNER = 'INNER',
  NET = 'net'
}

export const enum STACK_STYLE {
  IMAGE_Z_INDEX = 2,
  PROGRESS_VALUE = 0,
  PROGRESS_TOTAL = 100,
  PROGRESS_STROKE_WIDTH = 15,
  PROGRESS_SCALE_COUNT = 15,
  PROGRESS_SCALE_WIDTH = 5,
  PROGRESS_Z_INDEX = 1,
  PROGRESS_WIDTH = 80,
  PROGRESS_STEP = 10,
  MILLI_SECONDS = 100
}
